name: linter and tests

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup PHP
        uses: shivammathur/setup-php@2.15.0
        with:
          php-version: '8.0'

      - name: Run CI
        run: make ci

      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v3.0.0
        with:
          token: ${{ secrets.CC_TEST_REPORTER_ID }}
          file: build/logs/clover.xml
          debug: true
